language: c
os: linux
compiler:
  - gcc

# install newer camke version
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.20/cmake-3.20.3-Linux-x86_64.tar.gz
  - echo "3f8aeb2907d96cd4dc03955228b2be3f8b58cff65704bd9ce4599589253c8de8  cmake-3.20.0-linux-x86_64.tar.gz" > cmake_sha256.txt
  - sha256sum -c cmake_md5.txt
  - tar -xvf cmake-3.20.3-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.20.3-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - cmake .

services:
  - redis-server

script:
  - make
  - tests/test.sh