language: c
os: linux
compiler:
  - gcc

# install newer camke version
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.20/cmake-3.20.3-linux-x86_64.tar.gz
  - tar -xvf cmake-3.20.3-linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.20.3-linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - cmake .

services:
  - redis-server

script:
  - make
  - cd tests
  - ./test.sh