# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/858/bin/cmake

# The command to remove a file.
RM = /snap/cmake/858/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ogama/projects/redis-interval-module

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ogama/projects/redis-interval-module

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/858/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/858/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ogama/projects/redis-interval-module/CMakeFiles /home/ogama/projects/redis-interval-module//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ogama/projects/redis-interval-module/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named redis-interval-module

# Build rule for target.
redis-interval-module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 redis-interval-module
.PHONY : redis-interval-module

# fast build rule for target.
redis-interval-module/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/build
.PHONY : redis-interval-module/fast

src/hashmap.o: src/hashmap.c.o
.PHONY : src/hashmap.o

# target to build an object file
src/hashmap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/hashmap.c.o
.PHONY : src/hashmap.c.o

src/hashmap.i: src/hashmap.c.i
.PHONY : src/hashmap.i

# target to preprocess a source file
src/hashmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/hashmap.c.i
.PHONY : src/hashmap.c.i

src/hashmap.s: src/hashmap.c.s
.PHONY : src/hashmap.s

# target to generate assembly for a file
src/hashmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/hashmap.c.s
.PHONY : src/hashmap.c.s

src/interval-red-black-tree.o: src/interval-red-black-tree.c.o
.PHONY : src/interval-red-black-tree.o

# target to build an object file
src/interval-red-black-tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/interval-red-black-tree.c.o
.PHONY : src/interval-red-black-tree.c.o

src/interval-red-black-tree.i: src/interval-red-black-tree.c.i
.PHONY : src/interval-red-black-tree.i

# target to preprocess a source file
src/interval-red-black-tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/interval-red-black-tree.c.i
.PHONY : src/interval-red-black-tree.c.i

src/interval-red-black-tree.s: src/interval-red-black-tree.c.s
.PHONY : src/interval-red-black-tree.s

# target to generate assembly for a file
src/interval-red-black-tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/interval-red-black-tree.c.s
.PHONY : src/interval-red-black-tree.c.s

src/interval-set.o: src/interval-set.c.o
.PHONY : src/interval-set.o

# target to build an object file
src/interval-set.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/interval-set.c.o
.PHONY : src/interval-set.c.o

src/interval-set.i: src/interval-set.c.i
.PHONY : src/interval-set.i

# target to preprocess a source file
src/interval-set.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/interval-set.c.i
.PHONY : src/interval-set.c.i

src/interval-set.s: src/interval-set.c.s
.PHONY : src/interval-set.s

# target to generate assembly for a file
src/interval-set.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/interval-set.c.s
.PHONY : src/interval-set.c.s

src/interval.o: src/interval.c.o
.PHONY : src/interval.o

# target to build an object file
src/interval.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/interval.c.o
.PHONY : src/interval.c.o

src/interval.i: src/interval.c.i
.PHONY : src/interval.i

# target to preprocess a source file
src/interval.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/interval.c.i
.PHONY : src/interval.c.i

src/interval.s: src/interval.c.s
.PHONY : src/interval.s

# target to generate assembly for a file
src/interval.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/interval.c.s
.PHONY : src/interval.c.s

src/io.o: src/io.c.o
.PHONY : src/io.o

# target to build an object file
src/io.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/io.c.o
.PHONY : src/io.c.o

src/io.i: src/io.c.i
.PHONY : src/io.i

# target to preprocess a source file
src/io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/io.c.i
.PHONY : src/io.c.i

src/io.s: src/io.c.s
.PHONY : src/io.s

# target to generate assembly for a file
src/io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/io.c.s
.PHONY : src/io.c.s

src/linked-list.o: src/linked-list.c.o
.PHONY : src/linked-list.o

# target to build an object file
src/linked-list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/linked-list.c.o
.PHONY : src/linked-list.c.o

src/linked-list.i: src/linked-list.c.i
.PHONY : src/linked-list.i

# target to preprocess a source file
src/linked-list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/linked-list.c.i
.PHONY : src/linked-list.c.i

src/linked-list.s: src/linked-list.c.s
.PHONY : src/linked-list.s

# target to generate assembly for a file
src/linked-list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/linked-list.c.s
.PHONY : src/linked-list.c.s

src/redis-interval-module.o: src/redis-interval-module.c.o
.PHONY : src/redis-interval-module.o

# target to build an object file
src/redis-interval-module.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/redis-interval-module.c.o
.PHONY : src/redis-interval-module.c.o

src/redis-interval-module.i: src/redis-interval-module.c.i
.PHONY : src/redis-interval-module.i

# target to preprocess a source file
src/redis-interval-module.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/redis-interval-module.c.i
.PHONY : src/redis-interval-module.c.i

src/redis-interval-module.s: src/redis-interval-module.c.s
.PHONY : src/redis-interval-module.s

# target to generate assembly for a file
src/redis-interval-module.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/redis-interval-module.c.s
.PHONY : src/redis-interval-module.c.s

src/util.o: src/util.c.o
.PHONY : src/util.o

# target to build an object file
src/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/util.c.o
.PHONY : src/util.c.o

src/util.i: src/util.c.i
.PHONY : src/util.i

# target to preprocess a source file
src/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/util.c.i
.PHONY : src/util.c.i

src/util.s: src/util.c.s
.PHONY : src/util.s

# target to generate assembly for a file
src/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis-interval-module.dir/build.make CMakeFiles/redis-interval-module.dir/src/util.c.s
.PHONY : src/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... redis-interval-module"
	@echo "... src/hashmap.o"
	@echo "... src/hashmap.i"
	@echo "... src/hashmap.s"
	@echo "... src/interval-red-black-tree.o"
	@echo "... src/interval-red-black-tree.i"
	@echo "... src/interval-red-black-tree.s"
	@echo "... src/interval-set.o"
	@echo "... src/interval-set.i"
	@echo "... src/interval-set.s"
	@echo "... src/interval.o"
	@echo "... src/interval.i"
	@echo "... src/interval.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/linked-list.o"
	@echo "... src/linked-list.i"
	@echo "... src/linked-list.s"
	@echo "... src/redis-interval-module.o"
	@echo "... src/redis-interval-module.i"
	@echo "... src/redis-interval-module.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

