= Redis interval module

This module is an implementation of tree https://www.geeksforgeeks.org/interval-tree/[interval tree].

This data structure is similar to regular redis sorted set.

== Build & run

Requirements :

* cmake
* make

----
git clone https://github.com/ogama/redis-interval-module
cd redis-interval-module
cmake .
make
----

----
redis-server --loadmodule libredis-interval-module.so
----

== Commands

Syntax of an interval : 

----
double ::= "-"(0-9)+*("." (0-9)+)?
interval ::= ("[" | "]") (double | "-inf") "," (double | "+inf" | "inf") ("[" | "]")
----

.Examples
----
[-1,3.14] // between -1 included and 3.14 included
[-1,3.14[ // between -1 included and 3.14 excluded
]-1,3.14] // between -1 excluded and 3.14 included
]-1,3.14[ // between -1 excluded and 3.14 excluded
[0,+inf[ // from 0 to infinity
----

=== IADD <key> [<interval> <member>]...

Add an interval with an associated member in the interval set.

Time complexity : O(Log(n))
Return value : the number of intervals added in interval set

.Example
----
127.0.0.1:6379> IADD intervals 1,5 interval:1 10,15 interval:2
(integer) 2
----

=== ICARD <key>

Return the number of intervals in the interval set.

Time complexity : O(1)
Return value : the number of intervals in the given interval set

.Example
----
127.0.0.1:6379> ICARD intervals
(integer) 2
----

=== IREM <key> [<member>]...

Remove the interval by the member.

Time complexity : O(log(n))
Return value : the number of intervals removed from the interval set.

.Example
----
127.0.0.1:6379> IREM intervals interval:1 interval:2
(integer) 2
----

=== ICONTAINS <key> <double>

This command query an interval set and return the list of intervals that contains the value.

Time complexity : O(log(N)) where N is the number of items in interval set
Return value : the list of intervals.

.Retrun format
----
1) 1) member (string)
   2) lower bound inclusion (0 : excluded, 1 : included)
   3) lower bound value (double)
   4) upper bound inclusion (0 : excluded, 1 : included)
   5) upper bound value (double)
----

.Example
----
127.0.0.1:6379> IADD intervals 1,5 interval:1 10,15 interval:2
(integer) 2

127.0.0.1:6379> ICONTAINS intervals 11
1) 1) "interval:2"
   2) "1"
   3) "10"
   4) "1"
   5) "15"
----

=== IOVERLAPS <key> <interval>

Return the list of intervals that contains of overlaps the interval parameter.

Time complexity : O(log(N))
Return value : the list of intervals with the following format :

.Retrun format
----
1) 1) member (string)
   2) lower bound inclusion (0 : excluded, 1 : included)
   3) lower bound value (double)
   4) upper bound inclusion (0 : excluded, 1 : included)
   5) upper bound value (double)
----

.Example
----
127.0.0.1:6379> IADD intervals 1,5 interval:1 10,15 interval:2
(integer) 2

127.0.0.1:6379> IOVERLAPS intervals 0,11
1) 1) "interval:1"
   2) "1"
   3) "1"
   4) "1"
   5) "5"
2) 1) "interval:2"
   2) "1"
   3) "10"
   4) "1"
   5) "15"
----

=== ISCAN <key> <cursor> MATCH <pattern> [COUNT <amount>]

This command work like regular redis `SCAN`, `SSCAN`, `ZSCAN` and `HSCAN` commands.

Time complexity : O(N) Where N is the number of intervals to read specified by the `COUNT` clause (10 if the `COUNT` clause is specified).
Return format : the same format as the `SCAN` command, but every items is an interval.

.Item fortat
----
1) 1) member (string)
   2) lower bound inclusion (0 : excluded, 1 : included)
   3) lower bound value (double)
   4) upper bound inclusion (0 : excluded, 1 : included)
   5) upper bound value (double)
----

.Example
----
127.0.0.1:6379> IADD intervals 1,5 interval:1 10,15 interval:2
(integer) 2

127.0.0.1:6379> ISCAN intervals 0 MATCH *
1) (integer) 0
2) 1) 1) "interval:1"
      2) "1"
      3) "1"
      4) "1"
      5) "5"
   2) 1) "interval:2"
      2) "1"
      3) "10"
      4) "1"
      5) "15"
----